baseURL = "https://nathansmith.io/"
languageCode = "en-us"
title = "nathansmith.io"


[params]
hideMadeWithLine = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 2
