baseURL = "https://nathansmith.io/"
languageCode = "en-us"
title = "nathansmith.io"
# theme = 'hugo-bearblog'

# [permalinks]
#   blog = "/:slug/"
#   tags = "/blog/:slug"

[params]
hideMadeWithLine = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = true
    style = "monokai"
    tabWidth = 2
